--    Copyright Martin Eisengardt 2018 xworlds.eu
--    
--    This file is part of xwos.
--
--    xwos is free software: you can redistribute it and/or modify
--    it under the terms of the GNU General Public License as published by
--    the Free Software Foundation, either version 3 of the License, or
--    (at your option) any later version.
--
--    xwos is distributed in the hope that it will be useful,
--    but WITHOUT ANY WARRANTY; without even the implied warranty of
--    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--    GNU General Public License for more details.
--
--    You should have received a copy of the GNU General Public License
--    along with xwos.  If not, see <http://www.gnu.org/licenses/>.

-- TODO http://www.pjb.com.au/comp/lua/lcurses.html
--curses.new_chstr
--curses.newpad
--curses.initscr()
--curses.cbreak()
--curses.raw()
--curses.echo(false)
--curses.nl(false)
--curses.start_color()
--curses.use_default_colors()
--
--      pcall(curses.init_pair, 1, curses.COLOR_WHITE, curses.COLOR_BLUE)
--      pcall(curses.init_pair, 2, curses.COLOR_BLACK, curses.COLOR_BLUE)
--      pcall(curses.init_pair, 3, curses.COLOR_YELLOW, curses.COLOR_BLUE)
--      pcall(curses.init_pair, 4, curses.COLOR_BLACK, curses.COLOR_WHITE)
--      pcall(curses.init_pair, 5, curses.COLOR_BLACK, curses.COLOR_CYAN)
--      pcall(curses.init_pair, 6, curses.COLOR_CYAN, curses.COLOR_BLUE)
--      pcall(curses.init_pair, 7, curses.COLOR_CYAN, curses.COLOR_BLACK)
--      colors.default = curses.color_pair(1)
--      colors.disabled = curses.color_pair(2) + curses.A_BOLD
--      colors.title = curses.color_pair(3) + curses.A_BOLD
--      colors.button = curses.color_pair(4)
--      colors.widget = curses.color_pair(5)
--      colors.widget_disabled = curses.color_pair(5) + curses.A_BOLD
--      colors.current = curses.color_pair(1) + curses.A_BOLD
--      colors.subcurrent = curses.color_pair(6) + curses.A_BOLD
--      colors.cursor = curses.color_pair(7) + curses.A_BOLD
--curses.KEY_BACKSPACE
--KEY_DC
--newpad